# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Social links
googleplus_username: citations?user=mppCKUoAAAAJ&hl=en
orcid_username: 0000-0001-7032-5474

# Personal info
name: 温思嘉/Wen Sijia
email: sijiawen@buaa.edu.cn
# email_title: Email (Email title override)

# Dark Mode (true/false/never)
darkmode: false

# About Sectionprofile
# about_title: About Me (Use this to override about section title)
about_profile_image: images/WenSijia.jpg
about_content: | # this will include new lines to allow paragraphs
  Sijia Wen received a Doctoral degree from the State Key Laboratory of Virtual Reality Technology and Systems, School of Computer Science and Engineering, Beihang University in 2022. He is currently an assistant professor at the School of Artificial Intelligence, at Beihang University. His research interests include His research interests include computer vision, multi-source information fusion for visual perception, multimodal mixed reality, blockchain, and privacy-preserving computing in the field of artificial intelligence. He has published multiple research papers as the first or corresponding author in top-tier conferences and journals such as IEEE TIP, ACM TOG, SIGGRAPH Asia, IEEE TMM, and AAAI. He has undertaken several national research projects, serving as the principal investigator of the National Natural Science Foundation of China (NSFC) Youth Program, and participated in key, special, and general programs of NSFC. He holds over ten granted and pending patents domestically and internationally. He serves as a reviewer for top international conferences and journals, including CVPR, ICCV, and IEEE TPAMI. 

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        list_image: images/PolarSLAM.jpg
        quote: >
            Polarimetric Monocular Gaussian Splatting SLAM for Dense Surface Reconstruction
        description: | # this will include new lines to allow paragraphs
            We propose a polarization-augmented 3DGS-SLAM framework that integrates polarimetric cues with Gaussian splatting to improve scene reconstruction in challenging environments, by enhancing multi-view consistency and keyframe alignment through polarization and enforcing geometry-aware constraints. <br> 
            <i>Haitao Wang, **Sijia Wen#**, Bo Guo &nbsp;&nbsp;&nbsp; The 33rd ACM International Conference on Multimedia (MM), 2025.</i><br>
            [[PDF]]()[[Project]][[Dataset]]
      - layout: left
        list_image: images/High-Fidelity Polarimetric Implicit 3D Reconstruction via view dependent Physical Representation.jpg
        quote: >
            High-Fidelity Polarimetric Implicit 3D Reconstruction with View-Dependent Physical Representation
        description: | # this will include new lines to allow paragraphs
            We propose a polarimetric implicit 3D reconstruction method that integrates geometric and polarization data to generate high-quality meshes in complex scenes. A view-dependent physical representation analyzes subtle reflection properties, enhanced by a simple detection algorithm and optimized with ray tracing and polarization principles. <br> 
            <i>Yu Qiu, **Sijia Wen#**, Hainan Zhang, Zhiming Zheng &nbsp;&nbsp;&nbsp; The 39th Annual AAAI Conference on Artificial Intelligence (AAAI), 2025.</i><br>
            [[PDF]]()[[Project]][[Dataset]]
      - layout: left
        list_image: images/PolarDehaze.jpg
        quote: >
            Polarization State Attention Dehazing Network with a Simulated Polar-Haze Dataset
        description: | # this will include new lines to allow paragraphs
            We propose a haze simulation strategy using polarization cues to generate realistic hazy data. Using the Polar-Haze dataset, our polarization state attention dehazing network (PSADNet) combines an attention-based extraction module to capture key features and a dehazing module that enhances clarity while preserving polarization accuracy. <br> 
            <i>**Sijia Wen**, Yinqiang Zheng, Feng Lu &nbsp;&nbsp;&nbsp;IEEE Transactions on Multimedia, 2024.</i><br>
            [[PDF]](https://ieeexplore.ieee.org/document/10812839)[[Project]][[Dataset]]
      - layout: left
        list_image: images/DELS.jpg
        quote: >
            A Cross-Consistency Strategy for Clearer Perception in Low-Light Haze
        description: | # this will include new lines to allow paragraphs
            We introduce two key techniques: a cross-consistency dehazing-enhancement framework and a physically based simulation for generating a low-light hazy dataset. The framework improves image visibility by leveraging information from multiple sub-tasks, while the simulation creates ground truth datasets using a low-light hazy imaging model. <br> 
            <i>**Sijia Wen**, Chaoqun Zhuang, Yunfei Liu, Feng Lu &nbsp;&nbsp;&nbsp; Chinese Conference on Pattern Recognition and Computer Vision (PRCV) Poster, 2024.</i><br>
            [[PDF]](https://link.springer.com/chapter/10.1007/978-981-97-8685-5_5)[[Project]][[Dataset]]
      - layout: left
        list_image: images/in_vr.jpg
        quote: >
            3D Photography with One-shot Portrait Relighting
        description: | # this will include new lines to allow paragraphs
            In this paper, we present a physical-based framework that explicitly models 3D photography with relighting from a one-shot portrait. By extracting facial albedo and rendering realistic reflected light, our method is capable of generating novel views with different lighting conditions, which can faithfully deliver realistic rendered results. <br> 
            <i>Yunfei Liu</i>*<i>, **Sijia Wen***, Feng Lu &nbsp;&nbsp;&nbsp; IEEE International Symposium on Mixed and Augmented Reality (ISMAR) Poster, 2021.</i><br>
            [[PDF]](https://ieeexplore.ieee.org/abstract/document/9585876/)[[Project]][[Dataset]]
      - layout: left
        list_image: images/HR.jpg
        quote: >
            Polarization Guided Specular Reflection Separation
        description: | # this will include new lines to allow paragraphs
            In this paper, we derive a polarization guided model to incorporate the polarization information into a designed iteration optimization separation strategy to separate the specular reflection. The proposed polarization guided model can generate a polarization chromaticity image, which is able to reveal the intrinsic geometrical profile of the input image. <br> 
            <i>**Sijia Wen**, Yinqiang Zheng, Feng Lu &nbsp;&nbsp;&nbsp; IEEE Transactions on Image Processing (TIP), 30: 7280-7291, 2021.</i><br>
            [[PDF]](https://ieeexplore.ieee.org/document/9515579)[[Project]](https://github.com/wsj890411/Polar_HR)[[Dataset]](https://pan.baidu.com/s/1cSshmBUJpSDrlmHUqRN3KA)
      - layout: left
        list_image: images/JD.jpg
        quote: >
            A Sparse Representation Based Joint Demosaicing Method for Single-Chip Polarized Color Sensor
        description: | # this will include new lines to allow paragraphs
            For newly released single-chip polarized color sensor, we present a sparse representation-based optimization strategy that utilizes chromatic information and polarimetric information to jointly reconstruct the information. In addition, we build an optical data acquisition system to collect a dataset, which contains various sources of polarization. <br> 
            <i>**Sijia Wen**, Yinqiang Zheng, Feng Lu &nbsp;&nbsp;&nbsp; IEEE Transactions on Image Processing (TIP), 30: 4171-4182, 2021.</i><br>
            [[PDF]](https://ieeexplore.ieee.org/abstract/document/9397396/)[[Project]](https://github.com/wsj890411/JCPD_Model)[[Dataset]](https://www.dropbox.com/s/q377c1iktxwe22a/TIP_raw_dataset.zip?dl=0)
      - layout: left
        list_image: images/OL.jpg
        quote: >
          Convolutional Demosaicing Network for Joint Chromatic and Polarimetric Imagery
        description: | # this will include new lines to allow paragraphs
          In this letter, we collect the first chromatic-polarization dataset and propose a Chromatic-Polarization Demosaicing Network (CPDNet) to address this joint chromatic and polarimetric image demosaicing issue. The proposed CPDNet is composed of the residual block and the multi-task structure with the costumed loss function. <br>
          <i>**Sijia Wen**, Yinqiang Zheng, Feng Lu, Qinping Zhao &nbsp;&nbsp;&nbsp;Optics Letters, 44(22), 5646-5649, 2019.</i><br>
          [[PDF]](https://www.osapublishing.org/ol/abstract.cfm?uri=ol-44-22-5646)[[Project]](https://github.com/wsj890411/CPDNet)[[Dataset]](https://www.dropbox.com/s/4t3hw6i9tb0nvh2/OL.zip?dl=0)
      - layout: left
        list_image: images/IS.jpg
        quote: >
          Adaptive Synthesis of Indoor Scenes via Activity-Associated Object Relation Graphs
        description: | # this will include new lines to allow paragraphs
          <i>Qiang Fu, Xiaowu Chen, Xiaotian Wang, **Sijia Wen**, et al.<br> 
          ACM Transactions on Graphics, 2017, 36(6CD):201.1-201.13.</i><br>
          [[PDF]](https://dl.acm.org/doi/abs/10.1145/3130800.3130805)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
